version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Avaliação
  - avaliation
  - Família
  - inválidos
  - lastname
  - Matérias
  - Observações
  - senha
  - Tryber
ignoreWords: []
import: []
